=== RogerVFbr/MyCelebs/Serverless/http_add_picture/validation_schema/add_picture_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Add Picture Schema",
  "required": ["user_id", "img_name", "img_desc", "image"],
  "properties": {
    "user_id": {
      "type": "string",
      "default": "N.A."
    },
    "img_name": {
      "type": "string",
      "default": "N.A."
    },
    "img_desc": {
      "type": "string",
      "default": "N.A."
    },
    "image": {
      "type": "string"
    }
  }
}

=== RogerVFbr/MyCelebs/Serverless/tests/mock_add_picture_a.json
{
  "user_id": "dev@dev.com",
  "img_name": "KateMossTestPic",
  "img_desc": "This is a Kate Moss test pic.",
  "image": "/9j/4AAQSkZJRgABAQEAYABgAAD/4QBoRXhpZgAATU0AKgAAAAgABAEaAAUAAAABAAAAPgEbAAUAAAABAAAARgEoAAMAAAABAAIAAAExAAIAAAARAAAATgAAAAAAAABgAAAAAQAAAGAAAAABcGFpbnQubmV0IDQuMC4yMQAA/9sAQwACAQECAQECAgICAgICAgMFAwMDAwMGBAQDBQcGBwcHBgcHCAkLCQgICggHBwoNCgoLDAwMDAcJDg8NDA4LDAwM/9sAQwECAgIDAwMGAwMGDAgHCAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwM/8AAEQgBpAKWAwEiAAIRAQMRAf/EAB8AAAEFAQEBAQEBAAAAAAAAAAABAgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNicoIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/EAB8BAAMBAQEBAQEBAQEAAAAAAAABAgMEBQYHCAkKC//EALURAAIBAgQEAwQHBQQEAAECdwABAgMRBAUhMQYSQVEHYXETIjKBCBRCkaGxwQkjM1LwFWJy0QoWJDThJfEXGBkaJicoKSo1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoKDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uLj5OXm5+jp6vLz9PX29/j5+v/aAAwDAQACEQMRAD8A+Lf+CiS4/wCCgvx2xz/xcPX8/wDgyuK8dRck7hXsv/BRAbf+Cgfx29/iHr//AKcrivHgc9K5zrjsNVVVj296UnHT1pQrHtSqm1vm+WgYiEF6k+WkwAeOTSoMv/jQA1grcDrT4029uadwD/DSO/Hy8mgBWfb1oJyv4U+GPevNBxuC56ms+cAhjUR7WHPpTmjQL92m4bz+B8tTEZIz60c4EYjQgfLT0j2j5h1OKlCcdj+FITxRJgIybT1H5UEY7j8qdGpwd3604Q8fdrM0ERPXFKIxj7tKDilJ4oAjYAkf4U4NgU/yuOppdqhfvdqAp3sN2My9KmhhUxDNOWNSg9xxU0aKqDnH4UGhGsShaTC56U5nUORn9KFw4zuo1M7MQHApyIWHzcUBV3gbvzpxdQ+3NBotgRQo5pehpQrMOBTkXb97j60agNB3dKI1wGzxzUij0/SgKW6CjUBpAz1H5UPEcAjmkmRtw+WnxBgvTtVoBgiYnkcdqXy9h9PwqbOVX1Xr7U0r5nv3p3AiIAPUflS49x+VSCH5qaIWDdCRWcpK4DQu44yKd5eFpwRVbPfpTs1m3qA3y19KPLX0p26jdRcBpjX0o2qO1DHK1Lbx+Yv0o5rARGPI+79Km8tiv3ae0XHVRTw6jjdVKXcCPAx1FNCLipPLU9KWGIyHyk+Z26A1nUmkBGoUx5yoGM4PpShUdccfU11HhL4ZXWryruaW1WbCgi3aRMf72CK9a0P9kLQdbkDLqmpeewAdra3Msf6jg1hLFQjuyo0pS2Pn14rWGNTN5jH+HYen1qJ4Fd/kMeF5wTX1LY/8E87XVX2x3mowR7SyS3kRRJsemBWZq/7G954atnaCx0/UmjGAnnNGze/OKweOpp7mkcLUPmxYd54HWrEGnbZWWaRIVHUHlgPpXsGp/AtIruO01Lw5qGl3BI8ye2ZpUUevJIo1P4IeDNN1MWP/AAmH2e/uJAiefbs4wf7x2nH0ojjYydkwnRnFXZ5FfacunzMqzRzR54K1EBzjbjjvXt91+yV9u0e4utA1Ww1x7Q7bjyA8bMf91wM/8ABry7UvBdx4b1GazvI5ra+jbJhuEwSv+zjj8+a6I1GzHbcwY1jK9j/SnbY/7tXX0UO0jR7tsf3gf4aqPFiTafvL1rSMrsCORFI+UVHHD8x4qwirk84pSQuOc5rQCEx7ev8AKkjDB+RUxCyH6UGNRRcBh5pANzYyPyqTywKBGqtnvRdARyRYTnmqyH72KuzDKelVmhxP8vQ1pcBpwwxTZIgUOBU8kXyHFR5/+vQBB5O0D2ob7vUVMRvWkMQxxQBAp4pTUhj2r/D09KiDYUUAKQpFMEeBUm00h5FBmREnbUUkX93nmpd2BS5oAr4b0pDtU88fhU/ljn86jmjxQTUIZApH601UUjpUj89PSmgHFA1sMkCqvaotpDVNIflpp6VpFpEEOzcnNEaKi/rTj96jOaHPUD9+f+DW7/lHTruP+h51H/0RaUUn/Brcf+NdOu/9jzqP/oi0orqh8Jyy3Pxb/wCCiCL/AMPAvjpnj/i4Wv8A/pyuK8ewFPH4mvYf+Ch5/wCNgfx2z/0ULX//AE5XFePqPpj3rHqdUdgjbDtTiyue1IFDf3fzpcKn9304oewBwo3frTWlGflqWNA6balEaY27fxIrPnAjij3KN1PEK7hQE2v7elPHytkjA9TQ5aAIV8vNKsYcg9+1OZlcdjT1jAGfTpWZd0NMRHakKsf4amzSZ/8Ar0C5ENiyO1PC5HDZo3U6IYA4xQUR7+PepFcOPlpogy/A3VNbR4T7tADCi/3qbnrVjYp/h/SkKKCfl/SgmdxIlDDJ4pRCo+lPSH5e/Sk6rQbAPkZfQVKGBFJsUrzinIi7R92gCMxZYnd1qSFFCUuwf7NKAFFTzsCOQLle7DtUwiQj39aEt96bttOUbRyMfWj2jARE2L/s5pCqk0O3zbe3erECRsnzc0e0YEACpSjMfQdT1qaSJey5HtTVhYq3ej2jAdHGro1R9CfrUyRME9PWpFiQD5l5+lQ5O4FTGW+Xk96lWJQPepWjQEYGKNik0uYBgXJ7UrQ8dKesaq2f607dUsCq1u244VulKkQC4OQ3pU7/ADD5T83tTlhwnP3qAK/kj3/Kg2+fWrBTYuaTeKAIjbjFAKxcLyccVIzDp3PT3pYLdpCSVyPagCNYGuPr1xVuLSrhIBJJHGqN0B6mnQqunTbnVVkOR5LnIP1Pauk8N/DW58U6G/iTXLhtL8Nxvse5f5Xmx0ihXux6Zz3qJysrlRg5PQzfBfg288ca4NNsrFrhkG5iOCg9z0/Wvdfhl+ztouiaraxRxx3OoXg2yfaGaaONz+BwOvHSun+Ev7NviT4teD7eNbVvBHw+UiViR5d5fR+ssvB564xXuvgn4j+EPgY6aT4JsbfU57aNY9kaBpyMcsXrxcTmV9IndRwj3kafwK/ZUs9Anhl8RXt1rkkaeYkFvGNP0+0B/vKhxJ/wIc17d4a0XQfADSW2l2Gj6fcyL5pc7G2L/eK9CP8ACvG9T8e+IvGfhzddWcegQk4nmeXaXXtiPHHfnNcq3gw395HfSW63XmRlXmmfmMf3s15Nau57HdTocr0PffGHjT/hJZIbeO1sL63XI3LIEic9yPQ14B8U9Qjs9SkDWcluyEovnRCZCM9m5P41y3i7VdG8P5mbUpGhtudttH5iXJ9C+eMfTtXJ3f7ZOk+ErJ9P037LeXUpz89xuaAegTH9a4uWo3oelB00rM6vw141srHxJHpl3fTafcXEf7uKaQz296OPubuh9iBXdXX7MfhfxnpUlxLZW/8AaD9WjQIsrHuMdT/Kvk3xn+0tpOo38d1eaf5NvG2NRg/guVP/AC0jb+Bx9D1rrPgp+2zB4Nu3028vJfEGiQtvtJ/+XjYfuhT2YfrRy14e9ExnTpz0Oq8W/s06pZvLHoN1f29/ZliyPeOsioOcgj7oHPSsW/8Ahpea5pLaf420+GHUnAax1aGQyOx7LIpAz/vHmvVLrxta/FfwzpeseF/EEcN0GeKG6hbEcjn7sb+jZOD61yfiTxfd+LJYfDetXC6B4g1TMFnfTLiJpl7k++K9ChjaqfLI46mFps+cPEvw91L4a6zcLqAs49qOIJzHvt7vOSARjhsd8Vy1/wCBWn8MWOuWe77O0wt7uF+ZLZyDjJ9Dgkelem3vjK50eHXND8Xbbq2t5vsxlgbm2mBx530bG7H+1WNokX9nxatpU1ytwkSrcoVXyzerg4Ydfm5/Wvcw9aT1Z5eKpxi/dPJ5LT7JNJGDvWNyOuaakJLk8/N0FLdysbqZYlCXBkZ/LJy4T3qKy/0jdHuxJnv29a9KMtDlJG+X3559qQnI461LJbyIfmaNR6E1GAscnJ+aqAGDbV+Wjp1GKeWC9aR/mXP8PrQBFNynHNRsGD528etPDZf1U/rTpfuVpcBjcmmGLZA2cipM/OtOba42nvWgFNWGBTs81NJbqkZ7YHWqzkg/LQA5uV/Cogox2qRiFH6CmBcD7tAATlajAb+73qUHNGeKAIti/wB6mMG3fdp+V9qXFBmRE5Bpk4Yjhc8U9VIz8p60uaAK24D+tITn/d9asGOPuv14qOeNREcDvQTUIXj3CmCMe/FSqeOeDTSPmP8AOga2GGL5aZswal3Y68UhTJ3c0C5b6n76f8GuAx/wTr17/sedR/8ARFpRS/8ABrmMf8E7Ne/7HnUf/RFpRXbT+FHHU0kz8Wv+Ch6Z/wCCgfx1/wCyha//AOnK4rx+RdqjvXsH/BQ8D/h4F8duP+aha/8A+nK4ryONckcGudz1O6Ow2yAAO5fpxU5aMfw/pTo4ht6f/WpJl2bfl70nPSwPYbtAORSkZNKnzv0p2zYfu4rMz30GIf3vTtT5EMi46U5P9b+HWpKCvZkMUVSA9vXinZ/yKASGHX8aA9mGKEXLYx1qTNG7kUFciEMOOwpQc9qkjG8c/rR5fy96AEtz8gqRDlaYwMX3RmpDwOlABTW6VIYeP4akWPj7ooNBgOF/ClSH5qd5Wf4abskFADjDwflH505Yfl6UCBmXrQGaNduW4HpWPMACIGl8rIHGalij8xM/zFSRjy1x/KjmAI12rTWi3tu4qRF3r6U5B5a4HNHMBCsQVhlc++KkESnpxUsS71/HvTvJH+zRzAReVihI9mfepRBn+7S+R/u0cwEdGacV8tvu9fSkc5deG/KpAbjecUqxfNzj8qcDn86caAG+UP8AZ/Kjyh/s/lRn/Z/Sl4oATYFPbPtS55pFOJf0xUghy+7bQBG/5D3pvlrv25XdTraGW7uPLSGV2zwoHJrbs/CdtYec1/cKbzbvS2Xnyx/tkf0oeiuG7sZFxYlJtuCrxjJBHTNWooooNy8yzMM+i1reHvBWqeM42m0+Fbg4wWjPyoPYn734V6L8HP2eZNd1ORm0++1a7tSP9DUhVLerHsB9a46mMhBamnsZXSRyHgf4a3x1KwvtQs5LyS5k2afpYXc+on++R1WNM5PrzzX1R4L+DWh+FGtdU8W2kd34gULJaacjgwRDsscfY/XNdl4D+Alp8N7J9SulW98SXEIFxMf9XZ9cJH2VfU9+ea6zwJ8KYdUlk1nVFjkmjOI8NkR++c89e1fP4rMpN2R6mHwThv1OX8SeBPE3xeTzNWkutO0pMC102I4wv+1irF74fsPhHo25ms0nZVEKxLhoz6Mc8mt3x78WP7DeS001pLiS3G1VHBjPq5PX6CvDvG2u6tf6tc31xJHqmoyR7pG3BIbOP15wAenWvMjWnNnrQpKK1NrxX8d49J1/zLy4ma4jX5LRTmSX02eh9yCK8v8Aif8AtLaldaJPeXyrpujoTGsPmYZn9G9eo4GK4/xB4wh8a6nJoOkq1xdKyrKLVGmkDnOMEZLMcHhOmK8V/a78TWnw4jkm1drifV7dgi2xkxa2mMbYgOrSZ5YkkYIHBBrvweBc5XZjiJwgrmh4+/aMuL6PzJrmW7hXIginby4I/T5Ty3514f4u+MerXN3M76hHHk42RQlQo7AHNeR+IfjLq2o6lNdR/L5q7SG52j0A6Vl6ZrWoeU03ls285wSeffmvo6OVxirs8eeNUndHsj/GO/061X+0tq+YB5JHEh/3lPWug8MfFOS9sI7y3dStvIoaMfLlvYV4TJK09us26ZixxIsxy34e1aHgLWJNL1oozsElOEUn/PNXLC09gjiLs+xPhn+0hJ8ONVXUdPkmXR71Qbq0bn7Mx4LKv94da+m/FPxUh+KvhfRbzzLZkuJhb6mYiGWNpFCQzq38JBKZ9wa/O7TNXkh05ldlkt5mO8/xIe34/WvQPgP8ZLjR7GfSbp/9C1CMo+0/LhSWUr7ggGvJxOCfPfodkavMrHvnxj8Y6l8RvAV14iuobP8AtbR7ltA1NEX55RESlvMwzyxjROfevPP+Fp/YNK0e9uGYSW0b6dcl/wDlg3HzfT5f1q54d+ItvP431zTbqCP+z/EmjiKYq/IePaEl6/eO0ZI9TXlusMv/AAjmpRzTFry1KZA5jlYAiMj6rkn3FdNGnY4q0W3ZHQaz4shurmCbYyz28eJti/dz/eqpY+MN1h5gXzL26bCL/wA8h3zXV/CfwLp/jrw3Y3EkgtmkCW7uzD/SCvt1yc10+veGvD/g2G6+yzW66bbgo0/DESEYAJ/Lgc10+0a0MHSm9DzabXm0q1E14kkUB4DNxk1PpWrLf/NCyzK3oORXO6j4BufGN2ssmpW9vpiyFvOnJYn/AHVHf2IqxoWoto1xNpNrCI7dTu88IfMmP945+79OK6KczN0ZJXOugs1uZOZFTtljgA02e28uRFZuEGCf4TRYoy28e6CSTfyM/wARrUttPt72ItEzGFR5jq38LjoPpW1zMy7q2+zjj+LlfaoXAbjpTr67keTDD/WHgemKULu6jn1oAiMeGWnFdg6j8qkMSkfw02eP5fXjtVcwDWZSnP5VDNt8v5V5xxUgj4/io8vJ/irSmBUaNpFXjGOeacelWjFxTPK+X7tVcCpMN/K/LQPu1LLHmOowgx1/CgBvlj+6KXIUUrRgDNEkXFAEZPNRYODwan8rP8K/nSghaDMiSHKDOPxpskWeKsZ4qPHztQBX2Lnkc0jxB4vlGOKsCLf83HNIw2xN9e1BUtigIcKM8nPWlf5Vx9Kn8vd/DUc0XyelBKP3x/4Ndf8AlHbrv/Y86j/6ItKKP+DXVdv/AATs1z/seNQ/9EWlFdtP4UcVT4mfi5/wUQ/5SCfHL/soWv8A/pyuK8nhPyV61/wUL/5SB/HT/soevf8ApxuK8ogPyj6Vxy3OyOwRH52olP3frSy/NtpoGKQpbCp9+nSnimofnqTNBI2M/IKdmhP9d+FOfpQaDYj97609uVpty2NtTQEsufSgAgG5fbPNPaNAvy9e1OzRmg0EB4p8R4psX+sapM0ACjApYuUpM0RHKfjQZ+zQ6X7v4+lSW/8AqjTlPFI/TjrQaADxQx4qSDYENKACPuf/AF6ymA6M/uxQUz+NKvApGxioAVeBinxfcpqJuUHpTlXYKAHZpYP9XSxfcp1AB1oxRmjNACxcA0+oX5x9amoAKKKN1ADWXf8AhQqBTTiNwoxtoAKY7gHqvvntSsf/ANdFrb/vd0arLJnhWGQaALGmeH7jVG3xYjjXkyynav8AjUl1pv2WcqsyzSeqHKg1YlsJblVa8mZt3Hkpzt/Cr2m+Gbq51CG103TZZpAwZnLYXb/KonpqVGN2P0z7Z4dtVmhDSXlyNqIsW78uK63wp8MJtSjW81l4rc4y0cYzNKT2b0Fb3gTwHN4e0+41S8uJri+3bLa0hG4R/wCH4V7B8KvgTqHjx1uNWX/hH7OTb5gYb7q8Jxj/AHR9DXmYnHcq5Tqp0bsw/hj8MdU8eXFjoelWVnbeS28JZMAY0/2j13exr648DfCbTvg5pDWsbq2t3cZ82QLyo75roPAXwk8J/s6eH5ri2trWxuLuIMZJD/pEj4+9nr68VzupeMI/EjSyWskjiYFftTLh5D6D0HvXzmJxEm9D1aNOK3M82drN4jkhkee6t7XCtDCwxIT/AHye3sKq+JLu812c2sTR2Nrb8ogIRR/vYq/4R8DXeqWZuEzDah/NuH+7ISPQ1y3x01HS9C0kMZkiMp2w24bfc3be/ov41wSqyasz0lTjvE8v8f8AjHR/C928n2lry6hkPmCEHax/Hlv1rwH4l+KdU8Za/eQoqLJeHIgikZILeP8AvzlerHjCDI5ORxXqGraCupX0KNdQteTEvMipj7BHz0P97px05znNcRdw6bp1xdra3CWui6TIbvU7mQDdPjJKqP4pC2O/rzXdhaN0OpU0sjMPi+1/Yo+GFxrl81vb+LdagEujyFR5lshBzOVHQ8jZ+OcV+fPxIl1j4+eMZL7dfG1kkZofPJcu5PLEc8n1r6t8UfDjxh+2X8Q31rVLCVba5QRQwHpY26/6pB7nJz9K+i/g/wD8E8bHRtOhN5D83Hy7K9eOZU8NGy3OVZZOs/e2PzN0T9lTUr6P54Zmwf4VNbtz+yNrUMcDQw3Pl+hU1+yfg/8AY+0XTpI/9FjAA5XZ1rrpv2X9Au7fy/sccWOMhK4qnEFSTvE6P7BpW03Pw7HwC1LQIGW8tJnZiQGKfd/GsnUfg9eadcxyQq0kcZ3sxX5lr9wNf/Yf0DUdOP7iKRc5Ix9414/8RP8AgnTaTRySWUIVZM5K/wANbU8+/mMamRpK8T8w4/D0tjYI0alhfbQd3Y1R0K2ltTHt3b7Wb90B0Ubvnz7EZr7S+I37EGoeGrGSNYNybsKcE4xXjvif9mvUvD9+0iWEuydQCyjcHI9q9KOMhVRwywM4M85h1e4i1h5TlLy2JZO4kjZSAB+Y/KrOp6l9sQyRrtxaw7iF+UuqgH+Zropvh5dRXDL9naKaNNqgrhhyOla/hj4Tz3+ow6dcBleUNK7IvA+tdEa0ErnPOjJbnB2njC68ISvIqtJHbDNtbhyqSP6kjpj1FZr/ABButVsJYbiZrpY2MjxfdgR+w7bj7mtr4s6c29raPy4YrdjG0gG3co64rk9Gj0iy0ULKZGYSZwTgVteMo6EezOm8MeMJNeaO1uLy3tJlyV/d5jQ9B2+9711g0W7h8gpeWkkwUsWiyWfnq24fyridFvrZLja9jbwWrcpK0hZifpivbvg5aWl9aLNmCT7CwjaFoVd33erHtz0rllVs7MPZ30JvB+oWmqW1vHq9l9k8ngyxM24j+9/d/Lmtbxl4HhthHqmg3y39i7gSQ7cM4Prx1+nFe0/Db4H2vxFsbnS9PFhBL5n2iCyumy24A5GCMbWzkVjXv7LPiHwvpGr3EdrcaS1unmvFMu7yzz930X0I/SlRxkZXSMp0D561iyFvqrBfljR2Cgn5ugqMpsT72a6PxhpQOpyNtXmNfmRt3IJz9K5yVNgK8fN+dehRlzK5yTjykEQ4b/CpOlOMX+y350nk/wCyfzrUgSmuflp/lbTnaeKVj8lAECnig8ipAeKGPFAEHk4X7xqARfvv/rVZThaVjxVc4EDxfSq+/Aq1JCMU3aNv3a09oBX2qRSCLf8Ajx0q6NuPu03O0GqAqvBtXFN8rjpVi4Tcmf7wpn3UX2oAi6LimKeKs7qZJt2/N1xQZy2IB0proM/N0qxCRs+XpUc8W+bPtQTtqfvR/wAGv4Uf8E8Nc2/9DxqH/oi1opf+DYBNn/BPLXB/1PGof+iLWiu2n8KOOo7ybPxe/wCChv8Ayf8AfHL/ALKDr/8A6cbivH4x8xr2D/goccf8FAfjh/2UHX//AE43FeQbhurjludsdh9C/cH1p6jIoJ20h2voHTtSxDcn40IcvT84oM+SyuLimydKdninQkFW70G1NXCHpUgoUZpYznP1oJjD3h0f8VOGNw6daRgD8v
